### ISSUE TITLE
Variables no longer provide Sublime reference tooltips when hovering.

### ISSUE THREAD

**Issue by avencherus** [beefsack/GDScript-sublime#25]
![image](https://user-images.githubusercontent.com/13004169/69819316-564a4380-1207-11ea-8fa4-0c57c51748d9.png)

Nothing appears.

Still works with functions though, as shown below.

![image](https://user-images.githubusercontent.com/13004169/69819339-682be680-1207-11ea-9467-495bb5abed69.png)

**Comment by avencherus** [comment]
Bisected to 1f96aee02e428940699f48c975f13d90aeffebd9

**Comment by julfers** [comment]
I'll explain the relevant change, since I made it.

Sublime takes those definition hints from the `entity` top-level scope, but variable declarations are supposed to live under the `variable` scope according to [Sublime guidelines](https://www.sublimetext.com/docs/3/scope_naming.html#variable) and [example syntaxes](https://github.com/sublimehq/Packages/blob/759d6eed9b4beed87e602a23303a121c3a6c2fb3/C%23/tests/syntax_test_c%23.cs#L71-L73). Granted, that guidance seems odd: I would intuitively think that variable declarations should live under `entity.name`.

Of course, that's all pedantry, this is the actual problem that https://github.com/beefsack/GDScript-sublime/commit/1f96aee02e428940699f48c975f13d90aeffebd9 fixes:

![gdentity-defs](https://user-images.githubusercontent.com/3612218/69889904-63c40400-12c1-11ea-9b69-cbe0aa8113a2.png)

Previously, the `Ctrl/Cmd+R` menu listed every invocation of a function, when it's supposed to list just the function definitions.

**Comment by avencherus** [comment]
Thanks for the explanation.  I'm not versed in this area, so the parts requiring perquisite knowledge are a bit beyond me.

Is it never the intention to see and allow a this tooltip feature for variables that have a global scope?  I suppose I've gotten used to quickly jumping to definitions and usage, the same as with functions.

**Comment by julfers** [comment]
> Is it never the intention to see and allow a this tooltip feature for variables that have a global scope?

Yes, insofar as that seems to be what Sublime does out-of-the-box, but I don't claim to be an expert and I think there's more to this than I know.

Are you using a plugin that gives definition and reference hints on variables?

In other syntaxes, I see definition and reference hints on functions, but not variables. For example, a C# program with relevant scopes indicated:

```c#
using System;

public class Hello
{
  static string greeting = "Hello";
  //            ^^^^^^^^ variable.other.member.cs

  public static void Main()
  {
    greet("world");
    // <- meta.function-call.cs variable.function.cs
  }

  static void greet(string who)
  //          ^^^^^ entity.name.function.cs
  {
    Console.WriteLine(greeting + " " + who);
    //                ^^^^^^^^ variable.other.cs
  }
}
```

I do see a definition hint when hovering the `greet()` call on line 10, but *not* when hovering the `greeting` or `who` variables on line 17.

Here's the equivalent GDScript:

```gdscript
extends Node2D

var greeting = 'Hello'
#   ^^^^^^^^ variable.other.gdscript

func _ready():
  greet('world')
  # <- meta.function-call.gdscript variable.function.gdscript

func greet(who):
  #^^^^^ entity.name.function.gdscript
  print(greeting + ' ' + who)
  #     ^^^^^^^^ NOT variable.other
```

For me, definition hints in the GDScript here behave the same as in the built-in C#, but there is a difference: the reference to the `greeting` variable on line 13 doesn't have the `variable` scope. In stock Sublime, I think that difference is mostly invisible, but if I'm missing something or there's a plugin using `variable` scope to add "goto definition" hints, that might be why you'd get variable definition hints in C# and not GDScript.

**Comment by avencherus** [comment]
I see.  It wasn't a plug-in in my case, just that the older version of this package was allowing the same tooltip view of definitions and usage of variables.

Here's from the commit before.

![image](https://user-images.githubusercontent.com/13004169/70060947-17900100-15ec-11ea-8042-d6c6d17d4d56.png)

 I hadn't noticed until now, but it appears it wasn't really working all that well.

I will close this, since it's technically not an issue or regression.
